### PR TITLE
extend unit tests for torrent files to include large files and files with large offsets

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by ssiloti** [comment]
Are you sure about using exceptions for these errors? It seems like at least `extract_single_file` and `extract_single_file2` should catch the exceptions and store the error code in their `ec` parameters. Maybe `add_file_borrow` itself should have an `error_code` parameter.

**Comment by arvidn** [comment]
no, I'm not sure. on one hand I was thinking of making a precondition of `add_file` and `add_file_borrow` and then have `torrent_info` check it, and maybe that's better. using exceptions is similar to preconditions in the sense that they are fatal

**Comment by arvidn** [comment]
almost all functions taking integers have implied preconditions that they aren't allowed to be outside of some range. mostly those would be checked with asserts. so I think that's the option, against actually making `add_file_borrow` able to fail with an `error_code`. That's API incompatible with current version though. So I'm kind of inclined to lean towards declaring it preconditions. But then it should be asserts and no exceptions. The problem though is that it's a really complex API, and presumably most people creating torrents would fail to check and (potentially) generate invalid torrents

**Comment by arvidn** [comment]
I'll update this patch, but I'm looking at a higher priority issue right now

**Comment by arvidn** [comment]
I think exceptions is the right interface when the *client* calls `add_file()` or `add_file_borrow()`, but you're right that when it's used internally to parse a .torrent file, it should report it back in the `ec` parameter.

I think adding files large enough to hit these limits is truly an exceptional condition. It's not something you would expect to ever happen really. It's up there with `std::bad_alloc` (which `add_file()` throws today). I will tweak this a bit and see what you think.

**Comment by arvidn** [comment]
@ssiloti I updated this too. what do you think?

**Pull request merged**
