### PR TITLE
add missing file, v2_symlinks.torrent

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by ssiloti** [comment]
It also needs to be re-added to the `test_torrents` array in `test_torrent_info.cpp`.

**Comment by arvidn** [comment]
oh, it disappeared from there too?

**Comment by arvidn** [comment]
as far as I can tell, it's already in that list

**Comment by ssiloti** [comment]
I don't see it. The only reference to the file is on [line 933](https://github.com/ssiloti/libtorrent/blob/992c199192b543245e5fadc8103b57572b495a23/test/test_torrent_info.cpp#L933).

Looking back, the [initial commit](https://github.com/ssiloti/libtorrent/commit/34c15cc3d50db03f987b580faffeddc9c6861986) which added it was missing the file and the reference in `test_torrents` as well.

**Comment by arvidn** [comment]
ah, you're right

**Pull request merged**
